<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class EventChipsTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('live_report_players')->delete();

        \DB::table('live_report_players')->insert([
            0 => [
                'id' => 1,
                'name' => 'Niroshan Loganathan',
                'player_id' => 8,
                'poker_event_id' => 6,
                'current_chips' => 597000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:23:53',
                'updated_at' => '2022-09-18 09:23:53',
            ],
            1 => [
                'id' => 2,
                'name' => 'Kim Michael Enriquez',
                'player_id' => 9,
                'poker_event_id' => 6,
                'current_chips' => 494000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:23:53',
                'updated_at' => '2022-09-18 09:23:53',
            ],
            2 => [
                'id' => 3,
                'name' => 'Niroshan Loganathan',
                'player_id' => 8,
                'poker_event_id' => 6,
                'current_chips' => 597000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:25:51',
                'updated_at' => '2022-09-18 09:25:51',
            ],
            3 => [
                'id' => 4,
                'name' => 'Kim Michael Enriquez',
                'player_id' => 9,
                'poker_event_id' => 6,
                'current_chips' => 494000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:25:51',
                'updated_at' => '2022-09-18 09:25:51',
            ],
            4 => [
                'id' => 5,
                'name' => 'James Mendoza',
                'player_id' => 10,
                'poker_event_id' => 6,
                'current_chips' => 396000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:25:51',
                'updated_at' => '2022-09-18 09:25:51',
            ],
            5 => [
                'id' => 6,
                'name' => 'Joris Michl',
                'player_id' => 11,
                'poker_event_id' => 6,
                'current_chips' => 326000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:25:51',
                'updated_at' => '2022-09-18 09:25:51',
            ],
            6 => [
                'id' => 7,
                'name' => 'Jisang Jang',
                'player_id' => 12,
                'poker_event_id' => 6,
                'current_chips' => 312000,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:25:51',
                'updated_at' => '2022-09-18 09:25:51',
            ],
            7 => [
                'id' => 8,
                'name' => 'Niroshan Loganathan',
                'player_id' => 8,
                'poker_event_id' => 6,
                'current_chips' => 597000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            8 => [
                'id' => 9,
                'name' => 'Kim Michael Enriquez',
                'player_id' => 9,
                'poker_event_id' => 6,
                'current_chips' => 494000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            9 => [
                'id' => 10,
                'name' => 'James Mendoza',
                'player_id' => 10,
                'poker_event_id' => 6,
                'current_chips' => 396000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            10 => [
                'id' => 11,
                'name' => 'Joris Michl',
                'player_id' => 11,
                'poker_event_id' => 6,
                'current_chips' => 326000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            11 => [
                'id' => 12,
                'name' => 'Jisang Jang',
                'player_id' => 12,
                'poker_event_id' => 6,
                'current_chips' => 312000,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            12 => [
                'id' => 13,
                'name' => 'Mike Takayama',
                'player_id' => 13,
                'poker_event_id' => 6,
                'current_chips' => 299000,
                'payout' => 0.0,
                'rank' => 6,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:31:33',
                'updated_at' => '2022-09-18 09:31:33',
            ],
            13 => [
                'id' => 14,
                'name' => 'Niroshan Loganathan',
                'player_id' => 8,
                'poker_event_id' => 6,
                'current_chips' => 597000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            14 => [
                'id' => 15,
                'name' => 'Kim Michael Enriquez',
                'player_id' => 9,
                'poker_event_id' => 6,
                'current_chips' => 494000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            15 => [
                'id' => 16,
                'name' => 'James Mendoza',
                'player_id' => 10,
                'poker_event_id' => 6,
                'current_chips' => 396000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            16 => [
                'id' => 17,
                'name' => 'Joris Michl',
                'player_id' => 11,
                'poker_event_id' => 6,
                'current_chips' => 326000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            17 => [
                'id' => 18,
                'name' => 'Jisang Jang',
                'player_id' => 12,
                'poker_event_id' => 6,
                'current_chips' => 312000,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            18 => [
                'id' => 19,
                'name' => 'Mike Takayama',
                'player_id' => 13,
                'poker_event_id' => 6,
                'current_chips' => 299000,
                'payout' => 0.0,
                'rank' => 6,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            19 => [
                'id' => 20,
                'name' => 'Noel Araniel',
                'player_id' => 14,
                'poker_event_id' => 6,
                'current_chips' => 284000,
                'payout' => 0.0,
                'rank' => 7,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            20 => [
                'id' => 21,
                'name' => 'Jong Chan Park',
                'player_id' => 15,
                'poker_event_id' => 6,
                'current_chips' => 276000,
                'payout' => 0.0,
                'rank' => 8,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:32:32',
                'updated_at' => '2022-09-18 09:32:32',
            ],
            21 => [
                'id' => 22,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 30000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:35:28',
                'updated_at' => '2022-09-18 09:35:28',
            ],
            22 => [
                'id' => 23,
                'name' => 'Alexis Lim',
                'player_id' => 36,
                'poker_event_id' => 6,
                'current_chips' => 30000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:36:10',
                'updated_at' => '2022-09-18 09:36:10',
            ],
            23 => [
                'id' => 24,
                'name' => 'Alexis Lim',
                'player_id' => 36,
                'poker_event_id' => 6,
                'current_chips' => 30000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:37:18',
                'updated_at' => '2022-09-18 09:37:18',
            ],
            24 => [
                'id' => 25,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 30000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 09:37:58',
                'updated_at' => '2022-09-18 09:37:58',
            ],
            25 => [
                'id' => 26,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:00:55',
                'updated_at' => '2022-09-18 10:00:55',
            ],
            26 => [
                'id' => 27,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:01:54',
                'updated_at' => '2022-09-18 10:01:54',
            ],
            27 => [
                'id' => 28,
                'name' => 'Rodrigo Sequite',
                'player_id' => 37,
                'poker_event_id' => 6,
                'current_chips' => 62000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:01:54',
                'updated_at' => '2022-09-18 10:01:54',
            ],
            28 => [
                'id' => 29,
                'name' => 'Hazel Timonera',
                'player_id' => 38,
                'poker_event_id' => 6,
                'current_chips' => 50000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:01:54',
                'updated_at' => '2022-09-18 10:01:54',
            ],
            29 => [
                'id' => 30,
                'name' => 'Jhun Mondalo',
                'player_id' => 39,
                'poker_event_id' => 6,
                'current_chips' => 45000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:01:54',
                'updated_at' => '2022-09-18 10:01:54',
            ],
            30 => [
                'id' => 31,
                'name' => 'Vamerdino Magsakay',
                'player_id' => 40,
                'poker_event_id' => 6,
                'current_chips' => 26400,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:01:54',
                'updated_at' => '2022-09-18 10:01:54',
            ],
            31 => [
                'id' => 32,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:02:26',
                'updated_at' => '2022-09-18 10:02:26',
            ],
            32 => [
                'id' => 33,
                'name' => 'Rodrigo Sequite',
                'player_id' => 37,
                'poker_event_id' => 6,
                'current_chips' => 62000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:02:26',
                'updated_at' => '2022-09-18 10:02:26',
            ],
            33 => [
                'id' => 34,
                'name' => 'Hazel Timonera',
                'player_id' => 38,
                'poker_event_id' => 6,
                'current_chips' => 50000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:02:26',
                'updated_at' => '2022-09-18 10:02:26',
            ],
            34 => [
                'id' => 35,
                'name' => 'Jhun Mondalo',
                'player_id' => 39,
                'poker_event_id' => 6,
                'current_chips' => 45000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:02:26',
                'updated_at' => '2022-09-18 10:02:26',
            ],
            35 => [
                'id' => 36,
                'name' => 'Vamerdino Magsakay',
                'player_id' => 40,
                'poker_event_id' => 6,
                'current_chips' => 26400,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:02:26',
                'updated_at' => '2022-09-18 10:02:26',
            ],
            36 => [
                'id' => 37,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:03:40',
                'updated_at' => '2022-09-18 10:03:40',
            ],
            37 => [
                'id' => 38,
                'name' => 'Rodrigo Sequite',
                'player_id' => 37,
                'poker_event_id' => 6,
                'current_chips' => 62000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:03:40',
                'updated_at' => '2022-09-18 10:03:40',
            ],
            38 => [
                'id' => 39,
                'name' => 'Hazel Timonera',
                'player_id' => 38,
                'poker_event_id' => 6,
                'current_chips' => 50000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:03:40',
                'updated_at' => '2022-09-18 10:03:40',
            ],
            39 => [
                'id' => 40,
                'name' => 'Jhun Mondalo',
                'player_id' => 39,
                'poker_event_id' => 6,
                'current_chips' => 45000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:03:40',
                'updated_at' => '2022-09-18 10:03:40',
            ],
            40 => [
                'id' => 41,
                'name' => 'Vamerdino Magsakay',
                'player_id' => 40,
                'poker_event_id' => 6,
                'current_chips' => 26400,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:03:40',
                'updated_at' => '2022-09-18 10:03:40',
            ],
            41 => [
                'id' => 42,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:04:07',
                'updated_at' => '2022-09-18 10:04:07',
            ],
            42 => [
                'id' => 43,
                'name' => 'Rodrigo Sequite',
                'player_id' => 37,
                'poker_event_id' => 6,
                'current_chips' => 62000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:04:07',
                'updated_at' => '2022-09-18 10:04:07',
            ],
            43 => [
                'id' => 44,
                'name' => 'Hazel Timonera',
                'player_id' => 38,
                'poker_event_id' => 6,
                'current_chips' => 50000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:04:07',
                'updated_at' => '2022-09-18 10:04:07',
            ],
            44 => [
                'id' => 45,
                'name' => 'Jhun Mondalo',
                'player_id' => 39,
                'poker_event_id' => 6,
                'current_chips' => 45000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:04:07',
                'updated_at' => '2022-09-18 10:04:07',
            ],
            45 => [
                'id' => 46,
                'name' => 'Vamerdino Magsakay',
                'player_id' => 40,
                'poker_event_id' => 6,
                'current_chips' => 26400,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:04:07',
                'updated_at' => '2022-09-18 10:04:07',
            ],
            46 => [
                'id' => 47,
                'name' => 'Thijs Hilberts',
                'player_id' => 35,
                'poker_event_id' => 6,
                'current_chips' => 80000,
                'payout' => 0.0,
                'rank' => 1,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:08:01',
                'updated_at' => '2022-09-18 10:08:01',
            ],
            47 => [
                'id' => 48,
                'name' => 'Rodrigo Sequite',
                'player_id' => 37,
                'poker_event_id' => 6,
                'current_chips' => 62000,
                'payout' => 0.0,
                'rank' => 2,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:08:01',
                'updated_at' => '2022-09-18 10:08:01',
            ],
            48 => [
                'id' => 49,
                'name' => 'Hazel Timonera',
                'player_id' => 38,
                'poker_event_id' => 6,
                'current_chips' => 50000,
                'payout' => 0.0,
                'rank' => 3,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:08:01',
                'updated_at' => '2022-09-18 10:08:01',
            ],
            49 => [
                'id' => 50,
                'name' => 'Jhun Mondalo',
                'player_id' => 39,
                'poker_event_id' => 6,
                'current_chips' => 45000,
                'payout' => 0.0,
                'rank' => 4,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:08:01',
                'updated_at' => '2022-09-18 10:08:01',
            ],
            50 => [
                'id' => 51,
                'name' => 'Vamerdino Magsakay',
                'player_id' => 40,
                'poker_event_id' => 6,
                'current_chips' => 26400,
                'payout' => 0.0,
                'rank' => 5,
                'chips_before' => 0,
                'created_at' => '2022-09-18 10:08:02',
                'updated_at' => '2022-09-18 10:08:02',
            ],
        ]);
    }
}
