name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Cache PHP dependencies
      uses: actions/cache@v2
      id: vendor-cache
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
    - uses: actions/setup-node@v3
      with: 
        node-version: 16
    - name: Get Composer Cache Directory 2
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v2
      id: actions-cache
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Cache node_modules directory
      uses: actions/cache@v2
      id: node_modules-cache
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**/package-lock.json') }}
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install BACKPACK config
      run: composer config http-basic.backpackforlaravel.com 46246897 YLRizEJAen5G
    - name: Install Dependencies
      if: steps.vendor-cache.outputs.cache-hit != 'true'
      run: composer update -W --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install node dependencies
      if: steps.node_modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: RUN soketi globally
      run: ./node_modules/.bin/soketi start > /dev/null 2>&1 &
    - name: Generate key
      run: | 
        php artisan key:generate
        npm run build
        php artisan dusk:chrome-driver
        php artisan storage:link
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PEST
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:" 
      run: vendor/bin/pest --parallel
    - name: Browser Test - upgrade and start Chrome Driver
      run: |
        php artisan dusk:chrome-driver --detect
        ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
    - name: Run Dusk Tests
      run: |
        php artisan serve > /dev/null 2>&1 &
        php artisan pest:dusk
      env:
        SESSION_DRIVER: array
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"

    - name: deploy to site
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home
          cd adi
          cd web
          cd life-of-poker.boragnitrealty.xyz
          cd public_html
          pwd
          ./deploy.sh > deploy.txt

